# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice1', models.IntegerField()),
                ('dice2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1Position', models.IntegerField()),
                ('player2Position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seperate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seperMine', models.IntegerField()),
            ],
        ),
    ]
