# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('contents', models.TextField()),
                ('writer', models.CharField(max_length=30)),
            ],
        ),
    ]
